# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: turnstile 0.10.0 ruby lib

Gem::Specification.new do |s|
  s.name = "turnstile"
  s.version = "0.10.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Joshua Rangsikitpho"]
  s.date = "2014-06-20"
  s.description = "Process Sequencer"
  s.email = "rangsikitpho@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "lib/turnstile.rb",
    "lib/turnstile/db.rb",
    "lib/turnstile/turnstile_exception.rb",
    "spec/spec_helper.rb",
    "spec/turnstile/db_spec.rb",
    "spec/turnstile_spec.rb",
    "turnstile.gemspec",
    "turnstile/.document",
    "turnstile/.gitignore",
    "turnstile/.rspec",
    "turnstile/Gemfile",
    "turnstile/LICENSE.txt",
    "turnstile/README.rdoc",
    "turnstile/Rakefile",
    "turnstile/lib/turnstile.rb",
    "turnstile/spec/spec_helper.rb",
    "turnstile/spec/turnstile_spec.rb"
  ]
  s.homepage = "http://github.com/rangsikitpho/turnstile"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.1"
  s.summary = "Process Sequencer"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<aws-sdk>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<dotenv>, [">= 0"])
    else
      s.add_dependency(%q<aws-sdk>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<dotenv>, [">= 0"])
    end
  else
    s.add_dependency(%q<aws-sdk>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<dotenv>, [">= 0"])
  end
end

